# Generated by Django 3.2.5 on 2021-07-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
