# Generated by Django 3.2.5 on 2021-07-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_auto_20210710_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='image', max_length=100),
        ),
    ]
