# Generated by Django 3.2.5 on 2021-07-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0006_auto_20210712_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
