# Generated by Django 3.2.5 on 2021-07-13 04:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0007_profileimages_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
