# Generated by Django 3.2.5 on 2021-07-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0008_alter_profileimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimages',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clone.profileimages'),
        ),
    ]
