# Generated by Django 3.2.5 on 2021-07-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0014_follow_post_stream_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='User',
            new_name='user',
        ),
    ]
