# Generated by Django 3.2.5 on 2021-07-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0016_auto_20210715_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
